#!/bin/sh
set -e

if [ -d /run/systemd/system ]; then
	systemctl --system daemon-reload >/dev/null 2>&1 || true
fi

if [ "$1" = purge ] && command -v deb-systemd-helper >/dev/null 2>&1; then
	deb-systemd-helper purge sriov-vfs.service >/dev/null 2>&1 || true
	deb-systemd-helper purge sriov-vf-mappings.service >/dev/null 2>&1 || true
fi

exit 0
